# -*- coding: utf-8 -*-
"""linear regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pKWOs8JyB_39z2nS9P_pFh2ESZ8FsHv1
"""

pip install sklearn

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
X = ([178], [143], [123], [145], [176], [187], [134], [176], [156], [198], [109],[125])
Y = [11, 8, 6, 7, 8, 9, 10, 8, 7, 11, 6, 9]
print(X)
print(Y)
height = int(input("Enter the height = "))
clf = LinearRegression()
clf.fit(X,Y)
plt.plot(X, clf.predict(X), color='purple')
plt.scatter(X,Y)
accuracy = clf.score(X,Y)
predict = clf.predict([[height]])
print("accuracy = ", accuracy)
print("prediction = ", predict)