# -*- coding: utf-8 -*-
"""Suicides :(

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIfbtHTzMwPOBPP6eefECb55TWQR3N13
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

suicide = pd.read_csv('/content/master.csv')
suicide.head()

suicide.describe()

unique_country = suicide['country'].unique()
print(unique_country)

print(suicide['generation'].unique())

print(suicide['year'].unique())

alpha = 0.6
plt.figure(figsize=(15,25))
sns.countplot(y='country', data=suicide, alpha=alpha)
plt.title('Suicide')
plt.show()

plt.figure(figsize=(16,7))
sex = sns.countplot(hue='sex', x='sex', data = suicide)

plt.figure(figsize=(15,5))
bar_age= sns.barplot(x='sex', y= 'suicides_no', hue='age', data=suicide)